use_frameworks!

platform :ios, '9.0'

target 'XHSwiftExt_Example' do
  pod 'XHSwiftExt', :path => '../'

  target 'XHSwiftExt_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
